### ISSUE TITLE
跑测试的时候发生错误

### ISSUE THREAD

**Issue by Gs-Zhang** [thu-spmi/LABES#1]
RuntimeError: Error(s) in loading state_dict for SemiCVAE:
        Missing key(s) in state_dict: "u_encoder_q.embedding.weight", "u_encoder_q.gru.weight_ih_l0", "u_encoder_q.gru.weight_hh_l0", "u_encoder_q.gru.bias_ih_l0", "u_encoder_q.gru.bias_hh_l0", "u_encoder_q.gru.weight_ih_l0_reverse", "u_encoder_q.gru.weight_hh_l0_reverse", "u_encoder_q.gru.bias_ih_l0_reverse", "u_encoder_q.gru.bias_hh_l0_reverse", "m_encoder.embedding.weight", "m_encoder.gru.weight_ih_l0", "m_encoder.gru.weight_hh_l0", "m_encoder.gru.bias_ih_l0", "m_encoder.gru.bias_hh_l0", "m_encoder.gru.weight_ih_l0_reverse", "m_encoder.gru.weight_hh_l0_reverse", "m_encoder.gru.bias_ih_l0_reverse", "m_encoder.gru.bias_hh_l0_reverse", "qz_decoder.gru.weight_ih_l0", "qz_decoder.gru.weight_hh_l0", "qz_decoder.gru.bias_ih_l0", "qz_decoder.gru.bias_hh_l0", "qz_decoder.Wgen.weight", "qz_decoder.Wgen.bias", "qz_decoder.Wcp_u.weight", "qz_decoder.Wcp_u.bias", "qz_decoder.Wcp_m.weight", "qz_decoder.Wcp_m.bias", "qz_decoder.Wcp_pz.weight", "qz_decoder.Wcp_pz.bias", "qz_decoder.attn.attn.weight", "qz_decoder.attn.attn.bias", "qz_decoder.attn.v.weight".

是不是放的模型不对啊?

**Comment by Gs-Zhang** [comment]
python train.py -mode test -dataset multiwoz -method cvae -c eval_load_path=experiments/multiwoz/multiwoz_best beam_search=True

**Comment by 594zyc** [comment]
Try this: 
python train.py -mode test -dataset multiwoz -method bssmc -c eval_load_path=experiments/multiwoz/multiwoz_best beam_search=True
