### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by gouqi666** [thu-spmi/LABES#2]
为什么不加入dialog act（model_act = True)呢？
why don't add dialog act to decode response？

**Comment by 594zyc** [comment]
因为本文只关注dialog state作为随机变量的variational learning，dialog act作为另一个随机变量，加入后做会引入更高的复杂度，就没有在本工作中讨论而是作为了future work。

**Comment by ZhijianOu** [comment]
Good question!
Semi-supervised variational learning中考虑dialog act，我们有一个后继工作
https://arxiv.org/abs/2109.04314
Variational Latent-State GPT for Semi-supervised Task-Oriented Dialog Systems
Hong Liu, Yucheng Cai, Zhenru Lin, Zhijian Ou, Yi Huang, Junlan Feng

**Comment by gouqi666** [comment]
> 因为本文只关注dialog state作为随机变量的variational learning，dialog act作为另一个随机变量，加入后做会引入更高的复杂度，就没有在本工作中讨论而是作为了future work。



> Good question! Semi-supervised variational learning中考虑dialog act，我们有一个后继工作 https://arxiv.org/abs/2109.04314 Variational Latent-State GPT for Semi-supervised Task-Oriented Dialog Systems Hong Liu, Yucheng Cai, Zhenru Lin, Zhijian Ou, Yi Huang, Junlan Feng

感谢答复！我再去看看加入dialog act后的这篇paper

**Comment by gouqi666** [comment]
> 因为本文只关注dialog state作为随机变量的variational learning，dialog act作为另一个随机变量，加入后做会引入更高的复杂度，就没有在本工作中讨论而是作为了future work。

哦哦，好的，感谢回复！

**Comment by gouqi666** [comment]
> Good question! Semi-supervised variational learning中考虑dialog act，我们有一个后继工作 https://arxiv.org/abs/2109.04314 Variational Latent-State GPT for Semi-supervised Task-Oriented Dialog Systems Hong Liu, Yucheng Cai, Zhenru Lin, Zhijian Ou, Yi Huang, Junlan Feng

老师，你好，关于后续这篇文章，有一个小问题我没太看懂，文章里面的 sampling-then-forward-computation strategy不太明白具体是怎样实现的呢？怎么能减少时间复杂度的？可否告知一下

**Comment by gouqi666** [comment]
> Good question! Semi-supervised variational learning中考虑dialog act，我们有一个后继工作 https://arxiv.org/abs/2109.04314 Variational Latent-State GPT for Semi-supervised Task-Oriented Dialog Systems Hong Liu, Yucheng Cai, Zhenru Lin, Zhijian Ou, Yi Huang, Junlan Feng

老师，你好，关于后续这篇文章，有一个小问题我没太看懂，文章里面的 sampling-then-forward-computation strategy不太明白具体是怎样实现的呢？怎么能减少时间复杂度的？可否告知一下

**Comment by gouqi666** [comment]
> Good question! Semi-supervised variational learning中考虑dialog act，我们有一个后继工作 https://arxiv.org/abs/2109.04314 Variational Latent-State GPT for Semi-supervised Task-Oriented Dialog Systems Hong Liu, Yucheng Cai, Zhenru Lin, Zhijian Ou, Yi Huang, Junlan Feng

老师，你好，关于后续这篇文章，有一个小问题我没太看懂，文章里面的 sampling-then-forward-computation strategy不太明白具体是怎样实现的呢？怎么能减少时间复杂度的？可否告知一下

**Comment by gouqi666** [comment]
>

**Comment by ZhijianOu** [comment]
arxiv我们更新了到了v2（多了些描述），希望对你有帮助
