### ISSUE TITLE
Late splitting

### ISSUE THREAD

**Issue by IliasTriant** [thu-spmi/LABES#3]
In the dataset reader construct function: 

```
 def _construct(self):
        """
        construct encoded train, dev, test set.
        """
        vocab_path = cfg.dataset_path + 'vocab.word2idx.json'
        if not os.path.exists(self.dataset.data_path) or not os.path.exists(vocab_path):
            self.data = self.dataset.preprocess_data()
        else:
            self.data = json.loads(open(self.dataset.data_path, 'r', encoding='utf-8').read().lower())
        self.vocab.load_vocab(cfg.vocab_path)

        encoded_data = self._get_encoded_data(self.data)
        self.train, self.dev, self.test = self._split_data(encoded_data, cfg.split)
        random.shuffle(self.train)
        self.train_batch = self._construct_batches(self.train, 'train', cfg.batch_size)
        self.dev_batch = self._construct_batches(self.dev, 'dev', cfg.batch_size)
        self.test_batch = self._construct_batches(self.test, 'test', cfg.batch_size)
        self.batches = {'train': self.train_batch, 'dev': self.dev_batch, 'test': self.test_batch}
```

the splitting of the dataset into training-dev-test set occurs after the vocab creation and encoding of the data. IMHO, we may add bias in that way, as if only the train set had been used, then we may had a different frequency distribution, changing for example the `<unk>` words, during inference.

**Comment by 594zyc** [comment]
Thanks for the comment. I agree that constructing the vocabulary without seeing the test split is indeed a better practice and should be followed in NLP experiments. Since studying out-of-vocabulary is not our work's main goal, we will keep this part as it is for reproduction considerations.
